version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/public:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  node:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
